version: "3"

tasks:
  03-deploy-staging-cluster:
    desc: "Deploy argocd gitops staging target"
    cmds:
      - kubectl apply -f namespaces/argocd.yaml
      - kubectl create namespace staging
      - kubectl create namespace ingress-nginx
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f clusters/staging/application.yaml

  03-deploy-production-cluster:
    desc: "Deploy argocd gitops production target"
    cmds:
      - kubectl apply -f namespaces/argocd.yaml
      - kubectl create namespace production
      - kubectl create namespace ingress-nginx
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f clusters/production/application.yaml
      
  04-delete-staging-cluster:
    desc: "Deploy argocd gitops staging target"
    cmds:
      - kubectl delete -f clusters/staging/application.yaml
      - kubectl delete -f namespaces/argocd.yaml
      - kubectl delete namespace staging
      - kubectl delete namespace ingress-nginx

  04-delete-production-cluster:
    desc: "Deploy argocd gitops production target"
    cmds:
      - kubectl delete -f clusters/production/application.yaml
      - kubectl delete -f namespaces/argocd.yaml
      - kubectl delete namespace production
      - kubectl delete namespace ingress-nginx

  02-get-webui-password:
    desc: "Get password for argocd web ui admin user"
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode

  01-port-forward-webui:
    desc: "Port forward web UI to localhost on port 8080"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
