version: "3"

env:
  CLUSTER_NAME: stg-gke
  GCP_REGION: europe-central2
  GCP_ZONE: europe-central2-c
  # Set default gum style options
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"

tasks:
  gcp:01-init-cli:
    cmds:
      - gcloud init
    desc: "Authenticate and configure the gcloud CLI"

  gcp:02-enable-apis:
    cmds:
      - |
        gcloud services enable \
          compute.googleapis.com \
          container.googleapis.com \
          cloudresourcemanager.googleapis.com \
          iam.googleapis.com \
          secretmanager.googleapis.com \
          servicemanagement.googleapis.com \
          serviceusage.googleapis.com \
          monitoring.googleapis.com \
          logging.googleapis.com
    desc: "Enable necessary APIs"

  gcp:03-set-region-and-zone:
    cmds:
      - gcloud config set compute/region ${GCP_REGION}
      - gcloud config set compute/zone ${GCP_ZONE}
    desc: "Set default region and zone"

  gcp:04-create-vpc:
    cmds:
      - gcloud compute networks create ${CLUSTER_NAME} --subnet-mode=custom
    desc: "Create VPC"

  gcp:05-create-subnet:
    cmds:
      - |
        gcloud compute networks subnets create subnet-1 \
          --network=${CLUSTER_NAME} \
          --region=${GCP_REGION} \
          --range=10.0.0.0/20
    desc: "Create subnet"

  gcp:06-create-cluster:
    desc: "Create GKE cluster"
    vars:
      GCP_PROJECT_ID: movie-review-platform8451
    cmds:
      - |
        gcloud container clusters create ${CLUSTER_NAME} \
          --zone ${GCP_ZONE} \
          --network ${CLUSTER_NAME} \
          --subnetwork subnet-1 \
          --machine-type e2-standard-2 \
          --num-nodes 2 \
          --gateway-api=standard \
          --workload-pool={{.GCP_PROJECT_ID}}.svc.id.goog

  gcp:07-create-all:
    cmds:
      - task: gcp:02-enable-apis
      - task: gcp:03-set-region-and-zone
      - task: gcp:04-create-vpc
      - task: gcp:05-create-subnet
      - task: gcp:06-create-cluster
    desc: "Create the GCP network, subnet, firewall rules, and cluster in sequence"

  gcp:09-verify-all:
    desc: "Sanity-check all GCP & GKE resources for the active environment"
    cmds:
      - echo "===== ACTIVE CONTEXT ====="
      - echo "Project        : $(gcloud config get-value project)"
      - echo "Cluster        : $CLUSTER_NAME"
      - echo "Region         : $GCP_REGION"
      - echo "Zone           : $GCP_ZONE"

      - echo "\n===== CLUSTER INFO  ====="
      - kubectl cluster-info

      - echo "\n===== GKE CLUSTER ====="
      - gcloud container clusters list --region "$GCP_REGION"

      - echo "\n===== GKE NODE POOLS ====="
      - gcloud container node-pools list \
          --cluster "$CLUSTER_NAME" \
          --region "$GCP_REGION"

      - echo "\n===== KUBERNETES NODES ====="
      - kubectl get nodes -o wide

      - echo "\n===== COMPUTE VM INSTANCES ====="
      - gcloud compute instances list --zones "$GCP_ZONE"

      - echo "\n===== COMPUTE DISKS ====="
      - gcloud compute disks list

      - echo "\n===== CLOUD STORAGE BUCKETS ====="
      - gcloud storage buckets list || gsutil ls

      - echo "\n===== VPC NETWORKS ====="
      - gcloud compute networks list

      - echo "\n===== SUBNETWORKS ====="
      - gcloud compute networks subnets list --regions "$GCP_REGION"

      - echo "\n===== EXTERNAL IP ADDRESSES ====="
      - gcloud compute addresses list --regions "$GCP_REGION"

      - echo "\n===== FIREWALL RULES ====="
      - gcloud compute firewall-rules list

      - echo "\n===== ROUTES ====="
      - gcloud compute routes list

      - echo "\n===== SERVICE ACCOUNTS ====="
      - gcloud iam service-accounts list

      - echo "\n===== INGRESS ====="
      - kubectl get ingress -A

      - echo "\n===== VERIFY COMPLETE ====="

  gcp:10-wait-for-ingress:
    desc: Wait until GCE Ingress has an EXTERNAL-IP
    cmds:
      - |
        until kubectl get ingress -A \
          -o jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}' | grep -q .; do
          echo "Waiting for Ingress external IP..."
          sleep 10
        done
        echo "Ingress is ready ✅"

  gcp:11-clean-up:
    cmds:
      - gcloud container clusters delete ${CLUSTER_NAME} --zone ${GCP_ZONE} --quiet
      - gcloud compute networks subnets delete subnet-1 --region=${GCP_REGION} --quiet
      - gcloud compute networks delete ${CLUSTER_NAME} --quiet
    desc: "Delete the GCP network, subnet, firewall rules, and cluster in reverse sequence"

  gcp:08-connect-to-cluster:
    cmds:
      - gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${GCP_ZONE}
    desc: "Connect to the GKE cluster"

