version: "3"

includes:
  github-actions:
    taskfile: ./github-actions/Taskfile.yaml
    dir: ./github-actions

  api-node:
    taskfile: ./argocd-gitops/apps/api-node/Taskfile.yaml
    dir: ./argocd-gitops/apps/api-node

