version: "3"

includes:
  github-actions:
    taskfile: ./github-actions/Taskfile.yaml
    dir: ./github-actions

  gitops:
    taskfile: ./argocd-gitops/clusters/Taskfile.yaml
    dir: ./argocd-gitops/clusters
