version: "3"

vars:
  DATABASE_URL: "postgres://postgres:foobarbaz@localhost:5432/postgres"
  IMAGE_NAME: api-node
  IMAGE_REPO: "ghcr.io/twilight4"
  IMAGE_TAG: foobarbaz

tasks:

  generate-version-tag:
    desc: "Generate image tag based on latest git tag and commit"
    cmds:
      - cmd: |
          # Latest semver tag
          TAG=$(git describe --tags --abbrev=0 --match "[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo "0.0.0")
          # Short commit SHA
          SHA=$(git rev-parse --short HEAD)
          # Staging tag includes commit SHA, production tag is just semver
          echo "image_tag_staging=${TAG}-${SHA}" >> $GITHUB_OUTPUT
          echo "image_tag_prod=${TAG}" >> $GITHUB_OUTPUT

  check-new-tag-var:
    desc: "Check if NEW_TAG variable is set"
    cmds:
      - cmd: |
          if [ -z "{{.NEW_TAG}}" ] ; then
            echo "NEW_TAG var is required"
            exit 1
          fi

  update-image-tags:
    desc: "Recursively update image tags in files with the specified comment"
    vars:
      EXCLUDED_FILES: | 
        {{.TASKFILE_DIR}}/Taskfile.yaml
    cmds:
      - cmd: |
          if [ -z "{{.NEW_TAG}}" ] || [ -z "{{.IDENTIFIER_COMMENT}}" ] || [ -z "{{.STARTING_PATH}}" ]; then
            echo "Usage: task update-image-tags NEW_TAG=new-tag IDENTIFIER_COMMENT='# THIS_IS_MY_IMAGE_TAG' STARTING_PATH=/path"
            exit 1
          fi
      - cmd: |
          find "{{.STARTING_PATH}}" -type f \( -name "*.yaml" -o -name "*.yml" \) \
          -exec grep -l "{{.IDENTIFIER_COMMENT}}" {} \; | while read -r file; do
            if ! echo "{{ .EXCLUDED_FILES }}" | grep -q "$file"; then
              echo "Updating: $file"
              sed -i "s|\(\s*.*:\s*\).* \({{ .IDENTIFIER_COMMENT }}\)|\1{{ .NEW_TAG }} \2|" "$file"
            fi
          done

  update-staging-image-tags:
    desc: "Update image tags for staging config"
    cmds:
      - task: check-new-tag-var
      - task: update-image-tags
        vars:
          IDENTIFIER_COMMENT: "# STAGING_IMAGE_TAG"
          STARTING_PATH: "$(git rev-parse --show-toplevel)"

  update-production-image-tags:
    desc: "Update image tags for production config"
    cmds:
      - task: check-new-tag-var
      - task: update-image-tags
        vars:
          IDENTIFIER_COMMENT: "# PRODUCTION_IMAGE_TAG"
          STARTING_PATH: "$(git rev-parse --show-toplevel)"

  build-push-container-image-multi-arch:
    desc: "Build and push container image"
    cmds:
      - cmd: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t {{.IMAGE_REPO}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
            --push \
            --cache-from=type=registry,ref={{.IMAGE_REPO}}/{{.IMAGE_NAME}}:buildcache \
            --cache-to=type=registry,ref={{.IMAGE_REPO}}/{{.IMAGE_NAME}}:buildcache,mode=max \
            ../../app/api-node
