version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - npm install

  run:
    desc: Start node dev mode
    cmds:
      - npm run dev

  start:
    desc: Run node server
    cmds:
      - npm start

  test:
    desc: Run tests
    cmds:
      - npm test
