version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - npm install

  run:
    desc: Start node dev mode
    cmds:
      - |
        export FIRESTORE_PROJECT_ID=movie-review-platform8451
        export FIRESTORE_COLLECTION=movies
        npm run dev

  start:
    desc: Run node server
    cmds:
      - |
        export FIRESTORE_PROJECT_ID=movie-review-platform8451
        export FIRESTORE_COLLECTION=movies
        npm start

  test:
    desc: Run tests
    cmds:
      - |
        export FIRESTORE_PROJECT_ID=movie-review-platform8451
        export FIRESTORE_COLLECTION=movies
        npm test
